// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageKind } from "./MessageKind";

export interface ConsoleMessage { kind: MessageKind, message: string, }