// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Control = { "Dial": [string, number, number, number] } | { "Slider": [string, number, number, number] } | { "Toggle": [string, number, number] } | { "String": [string, string] };